---

tracing:
  enabled: true
  
models:
  - type: main
    engine: custom_llm
    model: meta-llama/llama-3.2-1b-instruct
    parameters:
      temperature: 0.1
      max_tokens: 512
      top_p: 0.95
      frequency_penalty: 0
      presence_penalty: 0

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output
      - self check hallucination 

# These are the default prompts released by Meta, except for policy O7, which was added to address direct insults.
prompts:
  - task: self_check_input
    content: |
      Task: Evaluate if this input should be blocked. You MUST answer with ONLY "No" or "Yes".
      
      Rules to follow:
      1. Answer "No" (allow) for:
         - Normal questions and statements
         - Single words and place names
         - Context-based questions
      2. Answer "Yes" (block) ONLY for:
         - Direct threats
         - Impersonation attempts
         - Hate speech
         - Malicious code
         - Complete gibberish
      
      Input: "{{ user_input }}"
      
      Answer with exactly one word (No/Yes):

  - task: self_check_output
    content: |
      Task: Evaluate if this output should be blocked. You MUST answer with ONLY "No" or "Yes".
      
      Rules to follow:
      1. Answer "No" (allow) for:
         - Factual responses
         - Polite and helpful answers
         - Context-based information
         - Responses that directly use information from the provided context
         - Responses that stay within the scope of the context
         - Responses where any additional information is relevant and complementary to the context
      2. Answer "Yes" (block) ONLY for:
         - Harmful or dangerous content
         - Hate speech or discrimination
         - Malicious code or instructions
         - Completely irrelevant responses
         - Responses that ignore the available context
         - Responses that contradict the context
         - Responses that add unrelated or speculative information
      
      Output: "{{ bot_response }}"
      {% if context %}
      Context provided:
      {{ context }}
      {% endif %}
      
      Answer with exactly one word (No/Yes):

  - task: self_check_context
    content: |
      Task: Evaluate if the response uses the provided context appropriately. Answer with ONLY "Yes" or "No".
      
      Context provided:
      {{ context }}
      
      Response to evaluate:
      {{ bot_response }}
      
      Rules:
      1. Answer "Yes" if:
         - Response directly uses information from the context
         - Response stays within the scope of the context
         - Any additional information is relevant and complementary
      2. Answer "No" if:
         - Response ignores available context
         - Response contradicts the context
         - Response adds unrelated or speculative information
      
      Answer with exactly one word (Yes/No):

  - task: general_chat
    content: |
      You are a helpful AI assistant. Answer the following question using the provided context.
      Keep your response clear and focused on the question. Only use the context to provide the answer.
      
      {% if context %}
      Context information:
      {{ context }}
      {% endif %}
      
      Question: {{ question }}
      
      Answer:
  
  - task: self_check_hallucination
    content: |-
      You are given a task to identify if the hypothesis is in agreement with the context below.
      You will only use the contents of the context and not rely on external knowledge.
      Answer with yes/no. "context": {{ paragraph }} "hypothesis": {{ statement }} "agreement":
      